#!/bin/sh

brew tap homebrew/services
brew tap caskroom/cask

brew cask install dropbox
brew cask install google-chrome
brew cask install iterm2
brew cask install google-drive
brew cask install atom
brew cask install skype
brew cask install java
brew cask install franz
brew cask install firefox

gem_install_or_update 'ru'
gem_install_or_update 'pulsar'

brew install 'mysql'
brew install 'htop'
brew install 'rbenv-aliases'
brew install 'rbenv-default-gems'
brew install 'fish'
brew install 'wget'
brew install 'phantomjs'
brew install 'elasticsearch'
brew install 'pwgen'
