# Ruby aliases
alias be "bundle exec"
alias bi "bundle install"
alias bo "bundle open"

# Console aliases
alias g "git"
alias gs "g s"
alias gd "g d"
alias gl "g l"
alias ga "g a"
alias gci "g ci"
alias gco "g co"
alias grb "g rb"
alias grb "g rb"
alias gpl "g pl"
alias gps "g ps"
alias l "ls"
alias la "ls -la"
alias ll "ls -l"
alias cat "bat"
alias curl "http"
